const { ObjectId } = require('mongodb');
const { authorIds } = require('./authors');

const bookIds = Array.from({ length: 50 }, () => new ObjectId());

const books = [
  // George Orwell
  { _id: bookIds[0],  title: '1984',                      authorId: authorIds[0], authorName: 'George Orwell',    publishedYear: 1949, price: 12.99, pages: 328, genres: ['dystopia', 'fiction', 'classic'], tags: ['surveillance', 'totalitarianism', 'political'], inStock: true,  rating: 4.7, reviews: 15420 },
  { _id: bookIds[1],  title: 'Animal Farm',               authorId: authorIds[0], authorName: 'George Orwell',    publishedYear: 1945, price: 9.99,  pages: 112, genres: ['satire', 'fiction', 'classic'],  tags: ['political', 'allegory', 'revolution'],        inStock: true,  rating: 4.5, reviews: 12100 },
  // García Márquez
  { _id: bookIds[2],  title: 'One Hundred Years of Solitude', authorId: authorIds[1], authorName: 'Gabriel García Márquez', publishedYear: 1967, price: 14.99, pages: 417, genres: ['magical realism', 'fiction', 'classic'], tags: ['family', 'Latin America', 'epic'], inStock: true, rating: 4.8, reviews: 19830 },
  { _id: bookIds[3],  title: 'Love in the Time of Cholera', authorId: authorIds[1], authorName: 'Gabriel García Márquez', publishedYear: 1985, price: 13.99, pages: 348, genres: ['romance', 'fiction'],           tags: ['love', 'aging', 'Colombia'],                 inStock: false, rating: 4.4, reviews: 8720  },
  // Toni Morrison
  { _id: bookIds[4],  title: 'Beloved',                   authorId: authorIds[2], authorName: 'Toni Morrison',    publishedYear: 1987, price: 13.99, pages: 321, genres: ['historical fiction', 'fiction'],    tags: ['slavery', 'trauma', 'ghost'],                inStock: true,  rating: 4.6, reviews: 9910  },
  { _id: bookIds[5],  title: 'Song of Solomon',           authorId: authorIds[2], authorName: 'Toni Morrison',    publishedYear: 1977, price: 12.99, pages: 341, genres: ['fiction', 'classic'],               tags: ['identity', 'heritage', 'family'],             inStock: true,  rating: 4.3, reviews: 4580  },
  // Haruki Murakami
  { _id: bookIds[6],  title: 'Norwegian Wood',            authorId: authorIds[3], authorName: 'Haruki Murakami',  publishedYear: 1987, price: 13.99, pages: 296, genres: ['romance', 'fiction'],               tags: ['love', 'loss', 'coming-of-age'],              inStock: true,  rating: 4.3, reviews: 22100 },
  { _id: bookIds[7],  title: 'Kafka on the Shore',        authorId: authorIds[3], authorName: 'Haruki Murakami',  publishedYear: 2002, price: 15.99, pages: 467, genres: ['magical realism', 'fiction'],       tags: ['surreal', 'fate', 'music'],                  inStock: true,  rating: 4.5, reviews: 17600 },
  { _id: bookIds[8],  title: '1Q84',                      authorId: authorIds[3], authorName: 'Haruki Murakami',  publishedYear: 2009, price: 17.99, pages: 944, genres: ['magical realism', 'thriller'],      tags: ['parallel worlds', 'cult', 'love'],            inStock: false, rating: 4.2, reviews: 11300 },
  // Chimamanda Adichie
  { _id: bookIds[9],  title: 'Purple Hibiscus',           authorId: authorIds[4], authorName: 'Chimamanda Ngozi Adichie', publishedYear: 2003, price: 12.99, pages: 307, genres: ['fiction', 'coming-of-age'],    tags: ['Nigeria', 'family', 'religion'],     inStock: true,  rating: 4.4, reviews: 6750  },
  { _id: bookIds[10], title: 'Half of a Yellow Sun',      authorId: authorIds[4], authorName: 'Chimamanda Ngozi Adichie', publishedYear: 2006, price: 14.99, pages: 433, genres: ['historical fiction', 'fiction'], tags: ['Nigeria', 'war', 'identity'],        inStock: true,  rating: 4.6, reviews: 8100  },
  { _id: bookIds[11], title: 'Americanah',                authorId: authorIds[4], authorName: 'Chimamanda Ngozi Adichie', publishedYear: 2013, price: 13.99, pages: 477, genres: ['fiction', 'romance'],           tags: ['race', 'immigration', 'identity'],   inStock: true,  rating: 4.5, reviews: 10200 },
  // Dostoevsky
  { _id: bookIds[12], title: 'Crime and Punishment',      authorId: authorIds[5], authorName: 'Fyodor Dostoevsky', publishedYear: 1866, price: 10.99, pages: 551, genres: ['psychological thriller', 'classic'], tags: ['guilt', 'morality', 'redemption'],           inStock: true,  rating: 4.7, reviews: 14800 },
  { _id: bookIds[13], title: 'The Brothers Karamazov',    authorId: authorIds[5], authorName: 'Fyodor Dostoevsky', publishedYear: 1880, price: 11.99, pages: 796, genres: ['fiction', 'classic', 'philosophy'],  tags: ['family', 'faith', 'morality'],               inStock: true,  rating: 4.8, reviews: 11200 },
  // Le Guin
  { _id: bookIds[14], title: 'The Left Hand of Darkness', authorId: authorIds[6], authorName: 'Ursula K. Le Guin', publishedYear: 1969, price: 12.99, pages: 286, genres: ['science fiction', 'classic'],       tags: ['gender', 'politics', 'alien worlds'],        inStock: true,  rating: 4.5, reviews: 8760  },
  { _id: bookIds[15], title: 'The Dispossessed',          authorId: authorIds[6], authorName: 'Ursula K. Le Guin', publishedYear: 1974, price: 12.99, pages: 311, genres: ['science fiction'],                  tags: ['anarchism', 'utopia', 'physics'],             inStock: false, rating: 4.4, reviews: 6430  },
  // Ishiguro
  { _id: bookIds[16], title: 'The Remains of the Day',    authorId: authorIds[7], authorName: 'Kazuo Ishiguro',   publishedYear: 1989, price: 13.99, pages: 256, genres: ['fiction', 'classic'],               tags: ['memory', 'regret', 'duty'],                  inStock: true,  rating: 4.5, reviews: 9150  },
  { _id: bookIds[17], title: 'Never Let Me Go',           authorId: authorIds[7], authorName: 'Kazuo Ishiguro',   publishedYear: 2005, price: 13.99, pages: 288, genres: ['dystopia', 'science fiction'],      tags: ['clones', 'mortality', 'friendship'],          inStock: true,  rating: 4.4, reviews: 12700 },
  // Atwood
  { _id: bookIds[18], title: "The Handmaid's Tale",       authorId: authorIds[8], authorName: 'Margaret Atwood',  publishedYear: 1985, price: 13.99, pages: 311, genres: ['dystopia', 'fiction', 'classic'],   tags: ['feminism', 'totalitarianism', 'religion'],   inStock: true,  rating: 4.6, reviews: 21500 },
  { _id: bookIds[19], title: 'Oryx and Crake',            authorId: authorIds[8], authorName: 'Margaret Atwood',  publishedYear: 2003, price: 13.99, pages: 374, genres: ['dystopia', 'science fiction'],      tags: ['biotech', 'extinction', 'future'],            inStock: true,  rating: 4.3, reviews: 7840  },
  // Tolstoy
  { _id: bookIds[20], title: 'War and Peace',             authorId: authorIds[9], authorName: 'Leo Tolstoy',      publishedYear: 1869, price: 14.99, pages: 1225, genres: ['historical fiction', 'classic'],   tags: ['Napoleonic wars', 'Russian society', 'epic'], inStock: true, rating: 4.6, reviews: 9870 },
  { _id: bookIds[21], title: 'Anna Karenina',             authorId: authorIds[9], authorName: 'Leo Tolstoy',      publishedYear: 1878, price: 12.99, pages: 864, genres: ['romance', 'fiction', 'classic'],   tags: ['adultery', 'society', 'tragedy'],             inStock: true,  rating: 4.7, reviews: 13600 },
  // Virginia Woolf
  { _id: bookIds[22], title: 'Mrs Dalloway',              authorId: authorIds[10], authorName: 'Virginia Woolf', publishedYear: 1925, price: 10.99, pages: 194, genres: ['modernist', 'fiction', 'classic'],  tags: ['stream-of-consciousness', 'London', 'time'],  inStock: true,  rating: 4.3, reviews: 6520  },
  { _id: bookIds[23], title: 'To the Lighthouse',         authorId: authorIds[10], authorName: 'Virginia Woolf', publishedYear: 1927, price: 10.99, pages: 209, genres: ['modernist', 'fiction', 'classic'],  tags: ['family', 'perception', 'loss'],               inStock: true,  rating: 4.4, reviews: 5890  },
  // Kafka
  { _id: bookIds[24], title: 'The Trial',                 authorId: authorIds[11], authorName: 'Franz Kafka',    publishedYear: 1925, price: 10.99, pages: 255, genres: ['absurdist', 'fiction', 'classic'],  tags: ['bureaucracy', 'guilt', 'existentialism'],    inStock: true,  rating: 4.4, reviews: 8150  },
  { _id: bookIds[25], title: 'The Metamorphosis',         authorId: authorIds[11], authorName: 'Franz Kafka',    publishedYear: 1915, price: 7.99,  pages: 96,  genres: ['absurdist', 'fiction', 'classic'],  tags: ['identity', 'alienation', 'family'],           inStock: true,  rating: 4.5, reviews: 10900 },
  // Allende
  { _id: bookIds[26], title: 'The House of the Spirits',  authorId: authorIds[12], authorName: 'Isabel Allende', publishedYear: 1982, price: 13.99, pages: 433, genres: ['magical realism', 'fiction'],       tags: ['Chile', 'family saga', 'politics'],           inStock: true,  rating: 4.5, reviews: 7320  },
  { _id: bookIds[27], title: 'Eva Luna',                  authorId: authorIds[12], authorName: 'Isabel Allende', publishedYear: 1987, price: 12.99, pages: 271, genres: ['fiction', 'adventure'],             tags: ['storytelling', 'Latin America', 'feminism'],  inStock: false, rating: 4.1, reviews: 3140  },
  // McCarthy
  { _id: bookIds[28], title: 'The Road',                  authorId: authorIds[13], authorName: 'Cormac McCarthy', publishedYear: 2006, price: 12.99, pages: 287, genres: ['dystopia', 'fiction'],              tags: ['post-apocalyptic', 'father-son', 'survival'], inStock: true,  rating: 4.5, reviews: 16200 },
  { _id: bookIds[29], title: 'No Country for Old Men',    authorId: authorIds[13], authorName: 'Cormac McCarthy', publishedYear: 2005, price: 12.99, pages: 309, genres: ['thriller', 'fiction'],             tags: ['violence', 'fate', 'Texas'],                  inStock: true,  rating: 4.4, reviews: 11400 },
  // Zadie Smith
  { _id: bookIds[30], title: 'White Teeth',               authorId: authorIds[14], authorName: 'Zadie Smith',    publishedYear: 2000, price: 13.99, pages: 448, genres: ['fiction', 'comedy'],                tags: ['multiculturalism', 'London', 'family'],       inStock: true,  rating: 4.3, reviews: 8920  },
  { _id: bookIds[31], title: 'On Beauty',                 authorId: authorIds[14], authorName: 'Zadie Smith',    publishedYear: 2005, price: 13.99, pages: 443, genres: ['fiction', 'comedy'],                tags: ['academia', 'race', 'art'],                    inStock: false, rating: 4.1, reviews: 4230  },
  // More books to round out to 50
  { _id: bookIds[32], title: 'Brave New World',           authorId: authorIds[8],  authorName: 'Margaret Atwood', publishedYear: 2016, price: 11.99, pages: 311, genres: ['dystopia', 'science fiction'],    tags: ['future', 'conditioning', 'freedom'],          inStock: true,  rating: 4.2, reviews: 18500 },
  { _id: bookIds[33], title: 'The Castle',                authorId: authorIds[11], authorName: 'Franz Kafka',    publishedYear: 1926, price: 10.99, pages: 328, genres: ['absurdist', 'fiction'],             tags: ['bureaucracy', 'alienation', 'village'],       inStock: true,  rating: 4.2, reviews: 4100  },
  { _id: bookIds[34], title: 'Sputnik Sweetheart',        authorId: authorIds[3],  authorName: 'Haruki Murakami', publishedYear: 1999, price: 12.99, pages: 210, genres: ['fiction', 'romance'],             tags: ['longing', 'mystery', 'travel'],               inStock: true,  rating: 4.2, reviews: 8900  },
  { _id: bookIds[35], title: 'The Wind-Up Bird Chronicle', authorId: authorIds[3], authorName: 'Haruki Murakami', publishedYear: 1994, price: 16.99, pages: 611, genres: ['magical realism', 'fiction'],     tags: ['identity', 'Japan', 'mystery'],               inStock: true,  rating: 4.6, reviews: 14200 },
  { _id: bookIds[36], title: 'The Idiot',                 authorId: authorIds[5],  authorName: 'Fyodor Dostoevsky', publishedYear: 1869, price: 11.99, pages: 656, genres: ['fiction', 'classic'],          tags: ['goodness', 'society', 'tragedy'],             inStock: false, rating: 4.5, reviews: 6700  },
  { _id: bookIds[37], title: 'A Gentleman in Moscow',     authorId: authorIds[7],  authorName: 'Kazuo Ishiguro', publishedYear: 2016, price: 15.99, pages: 462, genres: ['historical fiction', 'fiction'],   tags: ['Russia', 'confinement', 'elegance'],          inStock: true,  rating: 4.7, reviews: 19800 },
  { _id: bookIds[38], title: 'Demon Copperhead',          authorId: authorIds[2],  authorName: 'Toni Morrison', publishedYear: 2022, price: 18.99, pages: 560, genres: ['fiction', 'historical fiction'],    tags: ['opioid crisis', 'poverty', 'Appalachia'],    inStock: true,  rating: 4.5, reviews: 5400  },
  { _id: bookIds[39], title: 'The Blind Assassin',        authorId: authorIds[8],  authorName: 'Margaret Atwood', publishedYear: 2000, price: 14.99, pages: 521, genres: ['fiction', 'thriller'],           tags: ['sisters', 'war', 'secrets'],                  inStock: true,  rating: 4.4, reviews: 6200  },
  { _id: bookIds[40], title: 'Of Love and Shadows',       authorId: authorIds[12], authorName: 'Isabel Allende', publishedYear: 1984, price: 12.99, pages: 274, genres: ['fiction', 'romance'],              tags: ['Chile', 'dictatorship', 'resistance'],        inStock: true,  rating: 4.2, reviews: 2900  },
  { _id: bookIds[41], title: 'Pachinko',                  authorId: authorIds[4],  authorName: 'Chimamanda Ngozi Adichie', publishedYear: 2017, price: 16.99, pages: 496, genres: ['historical fiction', 'fiction'], tags: ['Korea', 'Japan', 'family saga'], inStock: true, rating: 4.7, reviews: 17400 },
  { _id: bookIds[42], title: 'The Power of the Dog',      authorId: authorIds[13], authorName: 'Cormac McCarthy', publishedYear: 1979, price: 14.99, pages: 231, genres: ['thriller', 'historical fiction'], tags: ['ranching', 'masculinity', 'Montana'],         inStock: true,  rating: 4.3, reviews: 7800  },
  { _id: bookIds[43], title: 'Mrs Bridge',                authorId: authorIds[10], authorName: 'Virginia Woolf', publishedYear: 1938, price: 9.99,  pages: 277, genres: ['fiction', 'classic'],              tags: ['marriage', 'domesticity', 'satire'],          inStock: false, rating: 4.0, reviews: 1820  },
  { _id: bookIds[44], title: 'The Years',                 authorId: authorIds[10], authorName: 'Virginia Woolf', publishedYear: 1937, price: 10.99, pages: 435, genres: ['modernist', 'fiction', 'classic'],  tags: ['time', 'family', 'history'],                  inStock: true,  rating: 4.2, reviews: 2640  },
  { _id: bookIds[45], title: 'NW',                        authorId: authorIds[14], authorName: 'Zadie Smith',    publishedYear: 2012, price: 13.99, pages: 304, genres: ['fiction'],                          tags: ['London', 'class', 'identity'],                inStock: true,  rating: 4.0, reviews: 3750  },
  { _id: bookIds[46], title: 'The Plague',                authorId: authorIds[5],  authorName: 'Fyodor Dostoevsky', publishedYear: 1972, price: 11.99, pages: 308, genres: ['fiction', 'classic'],          tags: ['epidemic', 'existentialism', 'community'],   inStock: true,  rating: 4.4, reviews: 8900  },
  { _id: bookIds[47], title: 'The Left Hand of God',      authorId: authorIds[6],  authorName: 'Ursula K. Le Guin', publishedYear: 1978, price: 11.99, pages: 244, genres: ['science fiction', 'fantasy'],  tags: ['religion', 'war', 'mercy'],                   inStock: true,  rating: 4.1, reviews: 3200  },
  { _id: bookIds[48], title: 'Sula',                      authorId: authorIds[2],  authorName: 'Toni Morrison', publishedYear: 1973, price: 11.99, pages: 174, genres: ['fiction', 'classic'],               tags: ['friendship', 'identity', 'community'],        inStock: true,  rating: 4.3, reviews: 4100  },
  { _id: bookIds[49], title: 'In the Skin of a Lion',     authorId: authorIds[12], authorName: 'Isabel Allende', publishedYear: 1987, price: 12.99, pages: 244, genres: ['historical fiction', 'fiction'],   tags: ['Toronto', 'immigrants', 'labor'],             inStock: false, rating: 4.3, reviews: 2100  },
];

module.exports = { books, bookIds };
